#ifndef __GLORKZ_H
#define __GLORKZ_H

#include "hdr.h"

struct text ltext[LOCSIZ] = {
	{ "You are standing at the end of a road before a small brick building.\r\nAround you is a forest.  A small stream flows out of the building and\r\ndown a gully.", 154 },
	{ "You have walked up a hill, still in the forest.  The road slopes back\r\ndown the other side of the hill.  There is a building in the distance.", 141 },
	{ "You are inside a building, a well house for a large spring.", 59 },
	{ "You are in a valley in the forest beside a stream tumbling along a\r\nrocky bed.", 78 },
	{ "You are in open forest, with a deep valley to one side.", 55 },
	{ "You are in open forest near both a valley and a road.", 53 },
	{ "At your feet all the water of the stream splashes into a 2-inch slit\r\nin the rock.  Downstream the streambed is bare rock.", 122 },
	{ "You are in a 20-foot depression floored with bare dirt.  Set into the\r\ndirt is a strong steel grate mounted in concrete.  A dry streambed\r\nleads into the depression.", 165 },
	{ "You are in a small chamber beneath a 3x3 steel grate to the surface.\r\nA low crawl over cobbles leads inward to the west.", 120 },
	{ "You are crawling over cobbles in a low passage.  There is a dim light\r\nat the east end of the passage.", 102 },
	{ "You are in a debris room filled with stuff washed in from the surface.\r\nA low wide passage with cobbles becomes plugged with mud and debris\r\nhere, but an awkward canyon leads upward and west.  A note on the wall\r\nsays \"Magic word XYZZY\".", 237 },
	{ "You are in an awkward sloping east/west canyon.", 47 },
	{ "You are in a splendid chamber thirty feet high.  The walls are frozen\r\nrivers of orange stone.  An awkward canyon and a good passage exit\r\nfrom east and west sides of the chamber.", 179 },
	{ "At your feet is a small pit breathing traces of white mist.  An east\r\npassage ends here except for a small crack leading on.", 124 },
	{ "You are at one end of a vast hall stretching forward out of sight to\r\nthe west.  There are openings to either side.  Nearby, a wide stone\r\nstaircase leads downward.  The hall is filled with wisps of white mist\r\nswaying to and fro almost as if alive.  A cold wind blows up the\r\nstaircase.  There is a passage at the top of a dome behind you.", 340 },
	{ "The crack is far too small for you to follow.", 45 },
	{ "You are on the east bank of a fissure slicing clear across the hall.\r\nThe mist is quite thick here, and the fissure is too wide to jump.", 136 },
	{ "This is a low room with a crude note on the wall.  The note says,\r\n\"You won't get it up the steps\".", 99 },
	{ "You are in the Hall of the Mountain King, with passages off in all\r\ndirections.", 79 },
	{ "You are at the bottom of the pit with a broken neck.", 52 },
	{ "You didn't make it.", 19 },
	{ "The dome is unclimbable.", 24 },
	{ "You are at the west end of the Twopit Room.  There is a large hole in\r\nthe wall above the pit at this end of the room.", 118 },
	{ "You are at the bottom of the eastern pit in the Twopit Room.  There is\r\na small pool of oil in one corner of the pit.", 117 },
	{ "You are at the bottom of the western pit in the Twopit Room.  There is\r\na large hole in the wall about 25 feet above you.", 121 },
	{ "You clamber up the plant and scurry through the hole at the top.", 64 },
	{ "You are on the west side of the fissure in the Hall of Mists.", 61 },
	{ "You are in a low N/S passage at a hole in the floor.  The hole goes\r\ndown to an E/W passage.", 92 },
	{ "You are in the south side chamber.", 34 },
	{ "You are in the west side chamber of the Hall of the Mountain King.\r\nA passage continues west and up here.", 105 },
	{ ">$<", 3 },
	{ "You can't get by the snake.", 27 },
	{ "You are in a large room, with a passage to the south, a passage to the\r\nwest, and a wall of broken rock to the east.  There is a large \"Y2\" on\r\na rock in the room's center.", 172 },
	{ "You are in a jumble of rock, with cracks everywhere.", 52 },
	{ "You're at a low window overlooking a huge pit, which extends up out of\r\nsight.  A floor is indistinctly visible over 50 feet below.  Traces of\r\nwhite mist cover the floor of the pit, becoming thicker to the right.\r\nMarks in the dust around the window would seem to indicate that\r\nsomeone has been here recently.  Directly across the pit from you and\r\n25 feet away there is a similar window looking into a lighted room.  A\r\nshadowy figure can be seen there peering back at you.", 476 },
	{ "You are in a dirty broken passage.  To the east is a crawl.  To the\r\nwest is a large passage.  Above you is a hole to another passage.", 134 },
	{ "You are on the brink of a small clean climbable pit.  A crawl leads\r\nwest.", 74 },
	{ "You are in the bottom of a small pit with a little stream, which\r\nenters and exits through tiny slits.", 102 },
	{ "You are in a large room full of dusty rocks.  There is a big hole in\r\nthe floor.  There are cracks everywhere, and a passage leading east.", 138 },
	{ "You have crawled through a very low wide passage parallel to and north\r\nof the Hall of Mists.", 93 },
	{ "You are at the west end of Hall of Mists.  A low wide crawl continues\r\nwest and another goes north.  To the south is a little passage 6 feet\r\noff the floor.", 156 },
	{ "You are in a maze of twisty little passages, all alike.", 55 },
	{ "You are in a maze of twisty little passages, all alike.", 55 },
	{ "You are in a maze of twisty little passages, all alike.", 55 },
	{ "You are in a maze of twisty little passages, all alike.", 55 },
	{ "Dead end", 8 },
	{ "Dead end", 8 },
	{ "Dead end", 8 },
	{ "You are in a maze of twisty little passages, all alike.", 55 },
	{ "You are in a maze of twisty little passages, all alike.", 55 },
	{ "You are in a maze of twisty little passages, all alike.", 55 },
	{ "You are in a maze of twisty little passages, all alike.", 55 },
	{ "You are in a maze of twisty little passages, all alike.", 55 },
	{ "Dead end", 8 },
	{ "You are in a maze of twisty little passages, all alike.", 55 },
	{ "Dead end", 8 },
	{ "You are on the brink of a thirty foot pit with a massive orange column\r\ndown one wall.  You could climb down here but you could not get back\r\nup.  The maze continues at this level.", 180 },
	{ "Dead end", 8 },
	{ "You have crawled through a very low wide passage parallel to and north\r\nof the Hall of Mists.", 93 },
	{ "You are at the east end of a very long hall apparently without side\r\nchambers.  To the east a low wide crawl slants up.  To the north a\r\nround two foot hole slants down.", 169 },
	{ "You are at the west end of a very long featureless hall.  The hall\r\njoins up with a narrow north/south passage.", 111 },
	{ "You are at a crossover of a high N/S passage and a low E/W one.", 63 },
	{ "Dead end", 8 },
	{ "You are at a complex junction.  A low hands and knees passage from the\r\nnorth joins a higher crawl from the east to make a walking passage\r\ngoing west.  There is also a large room above.  The air is damp here.", 209 },
	{ "You are in Bedquilt, a long east/west passage with holes everywhere.\r\nTo explore at random select north, south, up, or down.", 124 },
	{ "You are in a room whose walls resemble Swiss cheese.  Obvious passages\r\ngo west, east, NE, and NW.  Part of the room is occupied by a large\r\nbedrock block.", 155 },
	{ "You are at the east end of the Twopit Room.  The floor here is\r\nlittered with thin rock slabs, which make it easy to descend the pits.\r\nThere is a path here bypassing the pits to connect passages from east\r\nand west.  There are holes all over, but the only big one is on the\r\nwall directly over the west pit where you can't get to it.", 334 },
	{ "You are in a large low circular chamber whose floor is an immense slab\r\nfallen from the ceiling (Slab Room).  East and west there once were\r\nlarge passages, but they are now filled with boulders.  Low small\r\npassages go north and south, and the south one quickly bends west\r\naround the boulders.", 295 },
	{ "You are in a secret N/S canyon above a large room.", 50 },
	{ "You are in a secret N/S canyon above a sizable passage.", 55 },
	{ "You are in a secret canyon at a junction of three canyons, bearing\r\nnorth, south, and SE.  The north one is as tall as the other two\r\ncombined.", 143 },
	{ "You are in a large low room.  Crawls lead north, SE, and SW.", 60 },
	{ "Dead end crawl.", 15 },
	{ "You are in a secret canyon which here runs e/w.  It crosses over a\r\nvery tight canyon 15 feet below.  If you go down you may not be able\r\nto get back up.", 153 },
	{ "You are at a wide place in a very tight N/S canyon.", 51 },
	{ "The canyon here becomes too tight to go further south.", 54 },
	{ "You are in a tall E/W canyon.  A low tight crawl goes 3 feet north and\r\nseems to open up.", 89 },
	{ "The canyon runs into a mass of boulders -- dead end.", 52 },
	{ "The stream flows out through a pair of 1 foot diameter sewer pipes.\r\nIt would be advisable to use the exit.", 107 },
	{ "You are in a maze of twisty little passages, all alike.", 55 },
	{ "Dead end", 8 },
	{ "Dead end", 8 },
	{ "You are in a maze of twisty little passages, all alike.", 55 },
	{ "You are in a maze of twisty little passages, all alike.", 55 },
	{ "Dead end", 8 },
	{ "Dead end", 8 },
	{ "You are in a maze of twisty little passages, all alike.", 55 },
	{ "You are in a long, narrow corridor stretching out of sight to the\r\nwest.  At the eastern end is a hole through which you can see a\r\nprofusion of leaves.", 152 },
	{ "There is nothing here to climb.  Use \"up\" or \"out\" to leave the pit.", 68 },
	{ "You have climbed up the plant and out of the pit.", 49 },
	{ "You are at the top of a steep incline above a large room.  You could\r\nclimb down here, but you would not be able to climb up.  There is a\r\npassage leading back to the north.", 173 },
	{ "You are in the Giant Room.  The ceiling here is too high up for your\r\nlamp to show it.  Cavernous passages lead east, north, and south.  On\r\nthe west wall is scrawled the inscription, \"Fee fie foe foo\" [sic].", 208 },
	{ "The passage here is blocked by a recent cave-in.", 48 },
	{ "You are at one end of an immense north/south passage.", 53 },
	{ "You are in a magnificent cavern with a rushing stream, which cascades\r\nover a sparkling waterfall into a roaring whirlpool which disappears\r\nthrough a hole in the floor.  Passages exit to the south and west.", 207 },
	{ "You are in the Soft Room.  The walls are covered with heavy curtains,\r\nthe floor with a thick pile carpet.  Moss covers the ceiling.", 132 },
	{ "This is the Oriental Room.  Ancient oriental cave drawings cover the\r\nwalls.  A gently sloping passage leads upward to the north, another\r\npassage leads SE, and a hands and knees crawl leads west.", 196 },
	{ "You are following a wide path around the outer edge of a large cavern.\r\nFar below, through a heavy white mist, strange splashing noises can be\r\nheard.  The mist rises up through a fissure in the ceiling.  The path\r\nexits to the south and west.", 243 },
	{ "You are in an alcove.  A small NW path seems to widen after a short\r\ndistance.  An extremely tight tunnel leads east.  It looks like a very\r\ntight squeeze.  An eerie light can be seen at the other end.", 201 },
	{ "You're in a small chamber lit by an eerie green light.  An extremely\r\nnarrow tunnel exits to the west.  A dark corridor leads ne.", 129 },
	{ "You're in the Dark-Room.  A corridor leading south is the only exit.", 68 },
	{ "You are in an arched hall.  A coral passage once continued up and east\r\nfrom here, but is now blocked by debris.  The air smells of sea water.", 142 },
	{ "You're in a large room carved out of sedimentary rock.  The floor and\r\nwalls are littered with bits of shells embedded in the stone.  A\r\nshallow passage proceeds downward, and a somewhat steeper one leads\r\nup.  A low hands and knees passage enters from the south.", 263 },
	{ "You are in a long sloping corridor with ragged sharp walls.", 59 },
	{ "You are in a cul-de-sac about eight feet across.", 48 },
	{ "You are in an anteroom leading to a large passage to the east.  Small\r\npassages go west and up.  The remnants of recent digging are evident.\r\nA sign in midair here says \"Cave under construction beyond this point.\r\nProceed at own risk.  [Witt construction company]\"", 264 },
	{ "You are in a maze of twisty little passages, all different.", 59 },
	{ "You are at Witt's End.  Passages lead off in *all* directions.", 62 },
	{ "You are in a north/south canyon about 25 feet across.  The floor is\r\ncovered by white mist seeping in from the north.  The walls extend\r\nupward for well over 100 feet.  Suspended from some unseen point far\r\nabove you, an enormous two-sided mirror is hanging parallel to and\r\nmidway between the canyon walls.  (The mirror is obviously provided\r\nfor the use of the dwarves, who as you know, are extremely vain.)  A\r\nsmall window can be seen in either wall, some fifty feet up.", 474 },
	{ "You're at a low window overlooking a huge pit, which extends up out of\r\nsight.  A floor is indistinctly visible over 50 feet below.  Traces of\r\nwhite mist cover the floor of the pit, becoming thicker to the left.\r\nMarks in the dust around the window would seem to indicate that\r\nsomeone has been here recently.  Directly across the pit from you and\r\n25 feet away there is a similar window looking into a lighted room.  A\r\nshadowy figure can be seen there peering back at you.", 475 },
	{ "A large stalactite extends from the roof and almost reaches the floor\r\nbelow.  You could climb down it, and jump from it to the floor, but\r\nhaving done so you would be unable to reach it to climb back up.", 204 },
	{ "You are in a little maze of twisting passages, all different.", 61 },
	{ "You are at the edge of a large underground reservoir.  An opaque cloud\r\nof white mist fills the room and rises rapidly upward.  The lake is\r\nfed by a stream, which tumbles out of a hole in the wall about 10 feet\r\noverhead and splashes noisily into the water somewhere within the\r\nmist.  The only passage goes back toward the south.", 331 },
    { "Dead end", 8 },
    { "You are at the northeast end of an immense room, even larger than the\r\nGiant Room.  It appears to be a repository for the \"Adventure\"\r\nprogram.  Massive torches far overhead bathe the room with smoky\r\nyellow light.  Scattered about you can be seen a pile of bottles (all\r\nof them empty), a nursery of young beanstalks murmuring quietly, a bed\r\nof oysters, a bundle of black rods with rusty stars on their ends, and\r\na collection of brass lanterns.  Off to one side a great many dwarves\r\nare sleeping on the floor, snoring loudly.  A sign nearby reads: \"Do\r\nnot disturb the dwarves!\"  An immense mirror is hanging against one\r\nwall, and stretches to the other end of the room, where various other\r\nsundry objects can be glimpsed dimly in the distance.", 750 },
    { "You are at the southwest end of the Repository.  To one side is a pit\r\nfull of fierce green snakes.  On the other side is a row of small\r\nwicker cages, each of which contains a little sulking bird.  In one\r\ncorner is a bundle of black rods with rusty marks on their ends.  A\r\nlarge number of velvet pillows are scattered about on the floor.  A\r\nvast mirror stretches off to the northeast.  At your feet is a large\r\nsteel grate, next to which is a sign which reads, \"Treasure Vault.\r\nKeys in Main Office.\"", 504 },
    { "You are on one side of a large, deep chasm.  A heavy white mist rising\r\nup from below obscures all view of the far side.  A SW path leads away\r\nfrom the chasm into a winding corridor.", 183 },
    { "You are in a long winding corridor sloping out of sight in both\r\ndirections.", 76 },
    { "You are in a secret canyon which exits to the north and east.", 61 },
    { "You are in a secret canyon which exits to the north and east.", 61 },
    { "You are in a secret canyon which exits to the north and east.", 61 },
    { "You are on the far side of the chasm.  A ne path leads away from the\r\nchasm on this side.", 89 },
    { "You're in a long east/west corridor.  A faint rumbling noise can be\r\nheard in the distance.", 91 },
    { "The path forks here.  The left fork leads northeast.  A dull rumbling\r\nseems to get louder in that direction.  The right fork leads southeast\r\ndown a gentle slope.  The main corridor enters from the west.", 204 },
    { "The walls are quite warm here.  From the north can be heard a steady\r\nroar, so loud that the entire cave seems to be trembling.  Another\r\npassage leads south, and a low crawl goes east.", 185 },
    { "You are on the edge of a breath-taking view.  Far below you is an\r\nactive volcano, from which great gouts of molten lava come surging\r\nout, cascading back down into the depths.  The glowing rock fills the\r\nfarthest reaches of the cavern with a blood-red glare, giving every-\r\nthing an eerie, macabre appearance.  The air is filled with flickering\r\nsparks of ash and a heavy smell of brimstone.  The walls are hot to\r\nthe touch, and the thundering of the volcano drowns out all other\r\nsounds.  Embedded in the jagged roof far overhead are myriad twisted\r\nformations composed of pure white alabaster, which scatter the murky\r\nlight into sinister apparitions upon the walls.  To one side is a deep\r\ngorge, filled with a bizarre chaos of tortured rock which seems to\r\nhave been crafted by the devil himself.  An immense river of fire\r\ncrashes out from the depths of the volcano, burns its way through the\r\ngorge, and plummets into a bottomless pit far off to your left.  To\r\nthe right, an immense geyser of blistering steam erupts continuously\r\nfrom a barren island in the center of a sulfurous lake, which bubbles\r\nominously.  The far right wall is aflame with an incandescence of its\r\nown, which lends an additional infernal splendor to the already\r\nhellish scene.  A dark, foreboding passage exits to the south.", 1310 },
    { "You are in a small chamber filled with large boulders.  The walls are\r\nvery warm, causing the air in the room to be almost stifling from the\r\nheat.  The only exit is a crawl heading west, through which is coming\r\na low rumbling.", 228 },
    { "You are walking along a gently sloping north/south passage lined with\r\noddly shaped limestone formations.", 105 },
    { "You are standing at the entrance to a large, barren room.  A sign\r\nposted above the entrance reads:  \"Caution!  Bear in room!\"", 126 },
    { "You are inside a barren room.  The center of the room is completely\r\nempty except for some dust.  Marks in the dust lead away toward the\r\nfar end of the room.  The only exit is the way you came in.", 197 },
    { "You are in a maze of twisting little passages, all different.", 61 },
    { "You are in a little maze of twisty passages, all different.", 59 },
    { "You are in a twisting maze of little passages, all different.", 61 },
    { "You are in a twisting little maze of passages, all different.", 61 },
    { "You are in a twisty little maze of passages, all different.", 59 },
    { "You are in a twisty maze of little passages, all different.", 59 },
    { "You are in a little twisty maze of passages, all different.", 59 },
    { "You are in a maze of little twisting passages, all different.", 61 },
    { "You are in a maze of little twisty passages, all different.", 59 },
    { "Dead end", 8 }
};

struct text stext[LOCSIZ] = {
    { "You're at end of road again.", 28 },
    { "You're at hill in road.", 23 },
    { "You're inside building.", 23 },
    { "You're in valley.", 17 },
    { "You're in forest.", 17 },
    { "You're in forest.", 17 },
    { "You're at slit in streambed.", 28 },
    { "You're outside grate.", 21 },
    { "You're below the grate.", 23 },
    { "You're in Cobble Crawl.", 23 },
    { "You're in Debris Room.", 22 },
    { "You're in Bird Chamber.", 23 },
    { "You're at top of small pit.", 27 },
    { "You're in Hall of Mists.", 24 },
    { "You're on east bank of fissure.", 31 },
    { "You're in Nugget of Gold Room.", 30 },
    { "You're in Hall of Mt King.", 26 },
    { "You're at west end of Twopit Room.", 34 },
    { "You're in east pit.", 19 },
    { "You're in west pit.", 19 },
    { "You're at \"Y2\".", 15 },
    { "You're at window on pit.", 24 },
    { "You're in dirty passage.", 24 },
    { "You're in Dusty Rock room.", 26 },
    { "You're at west end of Hall of Mists.", 36 },
    { "You're at brink of pit.", 23 },
    { "You're at east end of Long Hall.", 32 },
    { "You're at west end of Long Hall.", 32 },
    { "You're at Complex Junction.", 27 },
    { "You're in Swiss Cheese room.", 28 },
    { "You're at east end of Twopit Room.", 34 },
    { "You're in Slab Room.", 20 },
    { "You're at junction of three secret canyons.", 43 },
    { "You're in secret E/W canyon above tight canyon.", 47 },
    { "You're in narrow corridor.", 26 },
    { "You're at steep incline above large room.", 41 },
    { "You're in Giant Room.", 21 },
    { "You're in cavern with waterfall.", 32 },
    { "You're in Soft Room.", 20 },
    { "You're in Oriental Room.", 24 },
    { "You're in Misty Cavern.", 23 },
    { "You're in Alcove.", 17 },
    { "You're in Plover Room.", 22 },
    { "You're in Dark-Room.", 20 },
    { "You're in Arched Hall.", 22 },
    { "You're in Shell Room.", 21 },
    { "You're in Anteroom.", 19 },
    { "You're at Witt's End.", 21 },
    { "You're in Mirror Canyon.", 24 },
    { "You're at window on pit.", 24 },
    { "You're at top of stalactite.", 28 },
    { "You're at Reservoir.", 20 },
    { "You're at NE end.", 17 },
    { "You're at SW end.", 17 },
    { "You're on SW side of chasm.", 27 },
    { "You're in sloping corridor.", 27 },
    { "You're on NE side of chasm.", 27 },
    { "You're in corridor.", 19 },
    { "You're at fork in path.", 23 },
    { "You're at junction with warm walls.", 35 },
    { "You're at Breath-taking View.", 29 },
    { "You're in Chamber of Boulders.", 30 },
    { "You're in limestone passage.", 28 },
    { "You're in front of barren room.", 31 },
    { "You're in Barren Room.", 22 }
};

/*struct text ptext[101] = {
    { "Set of keys", 11 },
    { "There are some keys on the ground here.", 39 },
    { "Brass lantern", 13 },
    { "There is a shiny brass lamp nearby.", 35 },
    { "There is a lamp shining nearby.", 31 },
    { "*Grate", 6 },
    { "The grate is locked.", 20 },
    { "The grate is open.", 18 },
    { "Wicker cage", 11 },
    { "There is a small wicker cage discarded nearby.", 46 },
    { "Black rod", 9 },
    { "A three foot black rod with a rusty star on an end lies nearby.", 63 },
    { "Black rod", 9 },
    { "A three foot black rod with a rusty mark on an end lies nearby.", 63 },
    { "*Steps", 6 },
    { "Rough stone steps lead down the pit.", 36 },
    { "Rough stone steps lead up the dome.", 35 },
    { "Little bird in cage", 19 },
    { "A cheerful little bird is sitting here singing.", 47 },
    { "There is a little bird in the cage.", 35 },
    { "*Rusty door", 11 },
    { "The way north is barred by a massive, rusty, iron door.", 55 },
    { "The way north leads through a massive, rusty, iron door.", 56 },
    { "Velvet pillow", 13 },
    { "A small velvet pillow lies on the floor.", 40 },
    { "*Snake", 6 },
    { "A huge green fierce snake bars the way!", 39 },
    { ">$<  (Chased away)", 18 },
    { "*Fissure", 8 },
    { ">$<", 3 },
    { "A crystal bridge now spans the fissure.", 39 },
    { "The crystal bridge has vanished!", 32 },
    { "*Stone tablet", 13 },
    { "A massive stone tablet embedded in the wall reads:\r\n\"Congratulations on bringing light into the Dark-Room!\"", 107 },
    { "Giant clam  >grunt!<", 20 },
    { "There is an enormous clam here with its shell tightly closed.", 61 },
    { "Giant oyster  >groan!<", 22 },
    { "There is an enormous oyster here with its shell tightly closed.", 63 },
    { "Interesting.  There seems to be something written on the underside of\r\nThe oyster.", 82 },
    { "\"Spelunker Today\"", 17 },
    { "There are a few recent issues of \"Spelunker Today\" magazine here.", 65 },
    { "Tasty food", 10 },
    { "There is food here.", 19 },
    { "Small bottle", 12 },
    { "There is a bottle of water here.", 32 },
    { "There is an empty bottle here.", 30 },
    { "There is a bottle of oil here.", 30 },
    { "Water in the bottle", 19 },
    { "Oil in the bottle", 17 },
    { "*Mirror", 7 },
    { ">$<", 3 },
    { "*Plant", 6 },
    { "There is a tiny little plant in the pit, murmuring \"Water, water, ...\"", 70 },
    { "The plant spurts into furious growth for a few seconds.", 55 },
    { "There is a 12-foot-tall beanstalk stretching up out of the pit,\r\nbellowing \"WATER!! WATER!!\"", 92 },
    { "The plant grows explosively, almost filling the bottom of the pit.", 66 },
    { "There is a gigantic beanstalk stretching all the way up to the hole.", 68 },
    { "You've over-watered the plant!  It's shriveling up!  It's, it's...", 66 },
    { "*Phony plant (seen in twopit room only when tall enough)", 56 },
    { ">$<", 3 },
    { "The top of a 12-foot-tall beanstalk is poking out of the west pit.", 66 },
    { "There is a huge beanstalk growing out of the west pit up to the hole.", 69 },
    { "*Stalactite", 11 },
    { ">$<", 3 },
    { "*Shadowy figure", 15 },
    { "The shadowy figure seems to be trying to attract your attention.", 64 },
    { "Dwarf's axe", 11 },
    { "There is a little axe here.", 27 },
    { "There is a little axe lying beside the bear.", 44 },
    { "*Cave drawings", 14 },
    { ">$<", 3 },
    { "*Pirate", 7 },
    { ">$<", 3 },
    { "*Dragon", 7 },
    { "A huge green fierce dragon bars the way!", 40 },
    { "Congratulations!  You have just vanquished a dragon with your bare\r\nhands!  (Unbelievable, isn't it?)", 101 },
    { "The body of a huge green dead dragon is lying off to one side.", 62 },
    { "*Chasm", 6 },
    { "A rickety wooden bridge extends across the chasm, vanishing into the\r\nmist.  A sign posted on the bridge reads, \"Stop! Pay troll!\"", 130 },
    { "The wreckage of a bridge (and a dead bear) can be seen at the bottom\r\nof the chasm.", 83 },
    { "*Troll", 6 },
    { "A burly troll stands by the bridge and insists you throw him a\r\ntreasure before you may cross.", 94 },
    { "The troll steps out from beneath the bridge and blocks your way.", 64 },
    { ">$<  (Chased away)", 18 },
    { "*Phony troll", 12 },
    { "The troll is nowhere to be seen.", 32 },
    { ">$<  (Bear uses rtext 141)", 26 },
    { "There is a ferocious cave bear eying you from the far end of the room!", 70 },
    { "There is a gentle cave bear sitting placidly in one corner.", 59 },
    { "There is a contented-looking bear wandering about nearby.", 57 },
    { ">$<  (Dead)", 11 },
    { "*Message in second maze", 23 },
    { "There is a message scrawled in the dust in a flowery script, reading:\r\n\"This is not the maze where the pirate leaves his treasure chest.\"", 137 },
    { "*Volcano and/or geyser", 22 },
    { ">$<", 3 },
    { "*Vending machine", 16 },
    { "There is a massive vending machine here.  The instructions on it read:\r\n\"Drop coins here to receive fresh batteries.\"", 117 },
    { "Batteries", 9 },
    { "There are fresh batteries here.", 31 },
    { "Some worn-out batteries have been discarded nearby.", 51 },
    { "*Carpet and/or moss", 19 },
    { ">$<", 3 },
    { "Large gold nugget", 17 },
    { "There is a large sparkling nugget of gold here!", 47 },
    { "Several diamonds", 16 },
    { "There are diamonds here!", 24 },
    { "Bars of silver", 14 },
    { "There are bars of silver here!", 30 },
    { "Precious jewelry", 16 },
    { "There is precious jewelry here!", 31 },
    { "Rare coins", 10 },
    { "There are many coins here!", 26 },
    { "Treasure chest", 14 },
    { "The pirate's treasure chest is here!", 36 },
    { "Golden eggs", 11 },
    { "There is a large nest here, full of golden eggs!", 48 },
    { "The nest of golden eggs has vanished!", 37 },
    { "Done!", 5 },
    { "Jeweled trident", 15 },
    { "There is a jewel-encrusted trident here!", 40 },
    { "Ming vase", 9 },
    { "There is a delicate, precious, Ming vase here!", 46 },
    { "The vase is now resting, delicately, on a velvet pillow.", 56 },
    { "The floor is littered with worthless shards of pottery.", 55 },
    { "The Ming vase drops with a delicate crash.", 42 },
    { "Egg-sized emerald", 17 },
    { "There is an emerald here the size of a plover's egg!", 52 },
    { "Platinum pyramid", 16 },
    { "There is a platinum pyramid here, 8 inches on a side!", 53 },
    { "Glistening pearl", 16 },
    { "Off to one side lies a glistening pearl!", 40 },
    { "Persian rug", 11 },
    { "There is a Persian rug spread out on the floor!", 47 },
    { "The dragon is sprawled out on a Persian rug!!", 45 },
    { "Rare spices", 11 },
    { "There are rare spices here!", 27 },
    { "Golden chain", 12 },
    { "There is a golden chain lying in a heap on the floor!", 53 },
    { "The bear is locked to the wall with a golden chain!", 51 },
    { "There is a golden chain locked to the wall!", 43 }
};*/

struct text rtext[RTXSIZ] = {
    { "Somewhere nearby is Colossal Cave, where others have found fortunes in\r\ntreasure and gold, though it is rumored that some who enter are never\r\nseen again.  Magic is said to work in the cave.  I will be your eyes\r\nand hands.  Direct me with commands of 1 or 2 words.  I should warn\r\nyou that I look at only the first five letters of each word, so you'll\r\nhave to enter \"northeast\" as \"ne\" to distinguish it from \"north\".\r\n(Should you get stuck, type \"help\" for some general hints.  For\r\ninformation on how to end your adventure, etc., type \"info\".)\r\n- - -\r\nThis program was originally developed by Will Crowther.  Most of the\r\nfeatures of the current program were added by Don Woods.  Address\r\ncomplaints about the UNIX version to Jim Gillogly (jim@rand.org).", 758 },
    { "A little dwarf with a big knife blocks your way.", 48 },
    { "A little dwarf just walked around a corner, saw you, threw a little\r\naxe at you (which missed), cursed, and ran away.", 117 },
    { "There is a threatening little dwarf in the room with you!", 57 },
    { "One sharp nasty knife is thrown at you!", 39 },
    { "None of them hit you!", 21 },
    { "One of them gets you!", 21 },
    { "A hollow voice says \"Plugh\".", 28 },
    { "There is no way to go that direction.", 37 },
    { "I am unsure how you are facing.  Use compass points or nearby objects.", 70 },
    { "I don't know in from out here.  Use compass points or name something\r\nin the general direction you want to go.", 110 },
    { "I don't know how to apply that word here.", 41 },
    { "I don't understand that!", 24 },
    { "I'm game.  Would you care to explain how?", 41 },
    { "Sorry, but I am not allowed to give more detail.  I will repeat the\r\nlong description of your location.", 103 },
    { "It is now pitch dark.  If you proceed you will likely fall into a pit.", 70 },
    { "If you prefer, simply type w rather than west.", 46 },
    { "Are you trying to catch the bird?", 33 },
    { "The bird is frightened right now and you cannot catch it no matter\r\nwhat you try.  Perhaps you might try later.", 111 },
    { "Are you trying to somehow deal with the snake?", 46 },
    { "You can't kill the snake, or drive it away, or avoid it, or anything\r\nlike that.  There is a way to get by, but you don't have the necessary\r\nresources right now.", 162 },
    { "Do you really want to quit now?", 31 },
    { "You fell into a pit and broke every bone in your body!", 54 },
    { "You are already carrying it!", 28 },
    { "You can't be serious!", 21 },
    { "The bird was unafraid when you entered, but as you approach it becomes\r\ndisturbed and you cannot catch it.", 106 },
    { "You can catch the bird, but you cannot carry it.", 48 },
    { "There is nothing here with a lock!", 34 },
    { "You aren't carrying it!", 23 },
    { "The little bird attacks the green snake, and in an astounding flurry\r\ndrives the snake away.", 92 },
    { "You have no keys!", 17 },
    { "It has no lock.", 15 },
    { "I don't know how to lock or unlock such a thing.", 48 },
    { "It was already locked.", 22 },
    { "The grate is now locked.", 24 },
    { "The grate is now unlocked.", 26 },
    { "It was already unlocked.", 24 },
    { "You have no source of light.", 28 },
    { "Your lamp is now on.", 20 },
    { "Your lamp is now off.", 21 },
    { "There is no way to get past the bear to unlock the chain, which is\r\nprobably just as well.", 90 },
    { "Nothing happens.", 16 },
    { "Where?", 6 },
    { "There is nothing here to attack.", 32 },
    { "The little bird is now dead.  Its body disappears.", 50 },
    { "Attacking the snake both doesn't work and is very dangerous.", 60 },
    { "You killed a little dwarf.", 26 },
    { "You attack a little dwarf, but he dodges out of the way.", 56 },
    { "With what?  Your bare hands?", 28 },
    { "Good try, but that is an old worn-out magic word.", 49 },
    { "I know of places, actions, and things.  Most of my vocabulary\r\ndescribes places and is used to move you there.  To move, try words\r\nlike forest, building, downstream, enter, east, west, north, south,\r\nup, or down.  I know about a few special objects, like a black rod\r\nhidden in the cave.  These objects can be manipulated using some of\r\nthe action words that I know.  Usually you will need to give both the\r\nobject and action words (in either order), but sometimes I can infer\r\nthe object from the verb alone.  Some objects also imply verbs; in\r\nparticular, \"inventory\" implies \"take inventory\", which causes me to\r\ngive you a list of what you're carrying.  The objects have side\r\neffects; for instance, the rod scares the bird.  Usually people having\r\ntrouble moving just need to try a few more words.  Usually people\r\ntrying unsuccessfully to manipulate an object are attempting something\r\nbeyond their (or my!) capabilities and should try a completely\r\ndifferent tack.  To speed the game you can sometimes move long\r\ndistances with a single word.  For example, \"building\" usually gets\r\nyou to the building from anywhere above ground except when lost in the\r\nforest.  Also, note that cave passages turn a lot, and that leaving a\r\nroom to the north does not guarantee entering the next from the south.\r\nGood luck!", 1315 },
    { "It misses!", 10 },
    { "It gets you!", 12 },
    { "OK", 2 },
    { "You can't unlock the keys.", 26 },
    { "You have crawled around in some little holes and wound up back in the\r\nmain passage.", 84 },
    { "I don't know where the cave is, but hereabouts no stream can run on\r\nthe surface for long.  I would try the stream.", 115 },
    { "I need more detailed instructions to do that.", 45 },
    { "I can only tell you what you see as you move about and manipulate\r\nthings.  I cannot tell you where remote things are.", 118 },
    { "I don't know that word.", 23 },
    { "What?", 5 },
    { "Are you trying to get into the cave?", 36 },
    { "The grate is very solid and has a hardened steel lock.  You cannot\r\nenter without a key, and there are no keys nearby.  I would recommend\r\nlooking elsewhere for the keys.", 170 },
    { "The trees of the forest are large hardwood oak and maple, with an\r\noccasional grove of pine or spruce.  There is quite a bit of under-\r\ngrowth, largely birch and ash saplings plus nondescript bushes of\r\nvarious sorts.  This time of year visibility is quite restricted by\r\nall the leaves, but travel is quite easy if you detour around the\r\nspruce and berry bushes.", 363 },
    { "Welcome to Adventure!!  Would you like instructions?", 52 },
    { "Digging without a shovel is quite impractical.  Even with a shovel\r\nprogress is unlikely.", 89 },
    { "Blasting requires dynamite.", 27 },
    { "I'm as confused as you are.", 27 },
    { "Mist is a white vapor, usually water, seen from time to time in\r\ncaverns.  It can be found anywhere but is frequently a sign of a deep\r\npit leading down to water.", 162 },
    { "Your feet are now wet.", 22 },
    { "I think I just lost my appetite.", 32 },
    { "Thank you, it was delicious!", 28 },
    { "You have taken a drink from the stream.  The water tastes strongly of\r\nminerals, but is not unpleasant.  It is extremely cold.", 126 },
    { "The bottle of water is now empty.", 33 },
    { "Rubbing the electric lamp is not particularly rewarding.  Anyway,\r\nnothing exciting happens.", 92 },
    { "Peculiar.  Nothing unexpected happens.", 38 },
    { "Your bottle is empty and the ground is wet.", 43 },
    { "You can't pour that.", 20 },
    { "Watch it!", 9 },
    { "Which way?", 10 },
    { "Oh dear, you seem to have gotten yourself killed.  I might be able to\r\nhelp you out, but I've never really done this before.  Do you want me\r\nto try to reincarnate you?", 168 },
    { "All right.  But don't blame me if something goes wr......\r\n--- Poof!! ---\r\nYou are engulfed in a cloud of orange smoke.  Coughing and gasping,\r\nyou emerge from the smoke and find....", 182 },
    { "You clumsy oaf, you've done it again!  I don't know how long I can\r\nkeep this up.  Do you want me to try reincarnating you again?", 129 },
    { "Okay, now where did I put my orange smoke?....  >poof!<\r\nEverything disappears in a dense cloud of orange smoke.", 112 },
    { "Now you've really done it!  I'm out of orange smoke!  You don't expect\r\nme to do a decent reincarnation without any orange smoke, do you?", 137 },
    { "Okay, if you're so smart, do it yourself!  I'm leaving!", 55 },
    { ">>> Messages 81 thru 90 are reserved for \"obituaries\". <<<", 58 },
    { "Sorry, but I no longer seem to remember how it was you got here.", 64 },
    { "You can't carry anything more.  You'll have to drop something first.", 68 },
    { "You can't go through a locked steel grate!", 42 },
    { "I believe what you want is right here with you.", 47 },
    { "You don't fit through a two-inch slit!", 38 },
    { "I respectfully suggest you go across the bridge instead of jumping.", 67 },
    { "There is no way across the fissure.", 35 },
    { "You're not carrying anything.", 29 },
    { "You are currently holding the following:", 40 },
    { "It's not hungry (it's merely pinin' for the fjords).  Besides, you\r\nhave no bird seed.", 86 },
    { "The snake has now devoured your bird.", 37 },
    { "There's nothing here it wants to eat (except perhaps you).", 58 },
    { "You fool, dwarves eat only coal!  Now you've made him *really* mad!!", 68 },
    { "You have nothing in which to carry it.", 38 },
    { "Your bottle is already full.", 28 },
    { "There is nothing here with which to fill the bottle.", 52 },
    { "Your bottle is now full of water.", 33 },
    { "Your bottle is now full of oil.", 31 },
    { "You can't fill that.", 20 },
    { "Don't be ridiculous!", 20 },
    { "The door is extremely rusty and refuses to open.", 48 },
    { "The plant indignantly shakes the oil off its leaves and asks, \"water?\"", 70 },
    { "The hinges are quite thoroughly rusted now and won't budge.", 59 },
    { "The oil has freed up the hinges so that the door will now move,\r\nalthough it requires some effort.", 98 },
    { "The plant has exceptionally deep roots and cannot be pulled free.", 65 },
    { "The dwarves' knives vanish as they strike the walls of the cave.", 64 },
    { "Something you're carrying won't fit through the tunnel with you.\r\nYou'd best take inventory and drop something.", 111 },
    { "You can't fit this five-foot clam through that little passage!", 62 },
    { "You can't fit this five-foot oyster through that little passage!", 64 },
    { "I advise you to put down the clam before opening it.  >strain!<", 63 },
    { "I advise you to put down the oyster before opening it.  >wrench!<", 65 },
    { "You don't have anything strong enough to open the clam.", 55 },
    { "You don't have anything strong enough to open the oyster.", 57 },
    { "A glistening pearl falls out of the clam and rolls away.  Goodness,\r\nthis must really be an oyster.  (I never was very good at identifying\r\nbivalves.)  Whatever it is, it has now snapped shut again.", 198 },
    { "The oyster creaks open, revealing nothing but oyster inside.  It\r\npromptly snaps shut again.", 92 },
    { "You have crawled around in some little holes and found your way\r\nblocked by a recent cave-in.  You are now back in the main passage.", 132 },
    { "There are faint rustling noises from the darkness behind you.", 61 },
    { "Out from the shadows behind you pounces a bearded pirate!  \"Har, har,\"\r\nhe chortles, \"I'll just take all this booty and hide it away with me\r\nchest deep in the maze!\"  He snatches your treasure and vanishes into\r\nthe gloom.", 223 },
    { "A sepulchral voice reverberating through the cave, says, \"Cave closing\r\nsoon.  All adventurers exit immediately through Main Office.\"", 133 },
    { "A mysterious recorded voice groans into life and announces:\r\n\"This exit is closed.  Please leave via Main Office.\"", 114 },
    { "It looks as though you're dead.  Well, seeing as how it's so close to\r\nclosing time anyway, I think we'll just call it a day.", 125 },
    { "The sepulchral voice intones, \"The cave is now closed.\"  As the echoes\r\nfade, there is a blinding flash of light (and a small puff of orange\r\nsmoke). . . .    As your eyes refocus, you look around and find...", 208 },
    { "There is a loud explosion, and a twenty-foot hole appears in the far\r\nwall, burying the dwarves in the rubble.  You march through the hole\r\nand find yourself in the Main Office, where a cheering band of\r\nfriendly elves carry the conquering adventurer off into the sunset.", 271 },
    { "There is a loud explosion, and a twenty-foot hole appears in the far\r\nwall, burying the snakes in the rubble.  A river of molten lava pours\r\nin through the hole, destroying everything in its path, including you!", 211 },
    { "There is a loud explosion, and you are suddenly splashed across the\r\nwalls of the room.", 87 },
    { "The resulting ruckus has awakened the dwarves.  There are now several\r\nthreatening little dwarves in the room with you!  Most of them throw\r\nknives at you!  All of them get you!", 177 },
    { "Oh, leave the poor unhappy bird alone.", 38 },
    { "I dare say whatever you want is around here somewhere.", 54 },
    { "I don't know the word \"stop\".  Use \"quit\" if you want to give up.", 65 },
    { "You can't get there from here.", 30 },
    { "You are being followed by a very large, tame bear.", 50 },
    { "If you want to end your adventure early, say \"quit\".  To suspend your\r\nadventure such that you can continue later, say \"suspend\" (or \"pause\"\r\nor \"save\").  To see what hours the cave is normally open, say \"hours\".\r\nTo see how well you're doing, say \"score\".  To get full credit for a\r\ntreasure, you must have left it safely in the building, though you get\r\npartial credit just for locating it.  You lose points for getting\r\nkilled, or for quitting, though the former costs you more.  There are\r\nalso points based on how much (if any) of the cave you've managed to\r\nexplore; in particular, there is a large bonus just for getting in (to\r\ndistinguish the beginners from the rest of the pack), and there are\r\nother ways to determine whether you've been through some of the more\r\nharrowing sections.  If you think you've found all the treasures, just\r\nkeep exploring for a while.  If nothing interesting happens, you\r\nhaven't found them all yet.  If something interesting *does* happen,\r\nit means you're getting a bonus and have an opportunity to garner many\r\nmore points in the Master's Section.  I may occasionally offer hints\r\nif you seem to be having trouble.  If I do, I'll warn you in advance\r\nhow much it will affect your score to accept the hints.  Finally, to\r\nsave paper, you may specify \"brief\", which tells me never to repeat\r\nthe full description of a place unless you explicitly ask me to.", 1398 },
    { "Do you indeed wish to quit now?", 31 },
    { "There is nothing here with which to fill the vase.", 50 },
    { "The sudden change in temperature has delicately shattered the vase.", 67 },
    { "It is beyond your power to do that.", 35 },
    { "I don't know how.", 17 },
    { "It is too far up for you to reach.", 34 },
    { "You killed a little dwarf.  The body vanishes in a cloud of greasy\r\nblack smoke.", 80 },
    { "The shell is very strong and is impervious to attack.", 53 },
    { "What's the matter, can't you read?  Now you'd best start over.", 62 },
    { "The axe bounces harmlessly off the dragon's thick scales.", 57 },
    { "The dragon looks rather nasty.  You'd best not try to get by.", 61 },
    { "The little bird attacks the green dragon, and in an astounding flurry\r\ngets burnt to a cinder.  The ashes blow away.", 116 },
    { "On what?", 8 },
    { "Okay, from now on I'll only describe a place in full the first time\r\nyou come to it.  To get the full description, say \"look\".", 126 },
    { "Trolls are close relatives with the rocks and have skin as tough as\r\nthat of a rhinoceros.  The troll fends off your blows effortlessly.", 136 },
    { "The troll deftly catches the axe, examines it carefully, and tosses it\r\nback, declaring, \"Good workmanship, but it's not valuable enough.\"", 138 },
    { "The troll catches your treasure and scurries away out of sight.", 63 },
    { "The troll refuses to let you cross.", 35 },
    { "There is no longer any way across the chasm.", 44 },
    { "Just as you reach the other side, the bridge buckles beneath the\r\nweight of the bear, which was still following you around.  You\r\nscrabble desperately for support, but as the bridge collapses you\r\nstumble back and fall into the chasm.", 234 },
    { "The bear lumbers toward the troll, who lets out a startled shriek and\r\nscurries away.  The bear soon gives up the pursuit and wanders back.", 139 },
    { "The axe misses and lands near the bear where you can't get at it.", 65 },
    { "With what?  Your bare hands?  Against *his* bear hands??", 56 },
    { "The bear is confused; he only wants to be your friend.", 54 },
    { "For crying out loud, the poor thing is already dead!", 52 },
    { "The bear eagerly wolfs down your food, after which he seems to calm\r\ndown considerably and even becomes rather friendly.", 120 },
    { "The bear is still chained to the wall.", 38 },
    { "The chain is still locked.", 26 },
    { "The chain is now unlocked.", 26 },
    { "The chain is now locked.", 24 },
    { "There is nothing here to which the chain can be locked.", 55 },
    { "There is nothing here to eat.", 29 },
    { "Do you want the hint?", 21 },
    { "Do you need help getting out of the maze?", 41 },
    { "You can make the passages look less alike by dropping things.", 61 },
    { "Are you trying to explore beyond the Plover Room?", 49 },
    { "There is a way to explore that region without having to worry about\r\nfalling into a pit.  None of the objects available is immediately\r\nuseful in discovering the secret.", 169 },
    { "Do you need help getting out of here?", 37 },
    { "Don't go west.", 14 },
    { "Gluttony is not one of the troll's vices.  Avarice, however, is.", 64 },
    { "Your lamp is getting dim.  You'd best start wrapping this up, unless\r\nYou can find some fresh batteries.  I seem to recall there's a vending\r\nmachine in the maze.  Bring some coins with you.", 190 },
    { "Your lamp has run out of power.", 31 },
    { "There's not much point in wandering around out here, and you can't\r\nexplore the cave without a lamp.  So let's just call it a day.", 130 },
    { "There are faint rustling noises from the darkness behind you.  As you\r\nturn toward them, the beam of your lamp falls across a bearded pirate.\r\nHe is carrying a large chest.  \"Shiver me timbers!\" he cries, \"I've\r\nbeen spotted!  I'd best hie meself off to the maze to hide me chest!\"\r\nWith that, he vanishes into the gloom.", 321 },
    { "Your lamp is getting dim.  You'd best go back for those batteries.", 66 },
    { "Your lamp is getting dim.  I'm taking the liberty of replacing the\r\nbatteries.", 78 },
    { "Your lamp is getting dim, and you're out of spare batteries.  You'd\r\nbest start wrapping this up.", 97 },
    { "I'm afraid the magazine is written in Dwarvish.", 47 },
    { "\"This is not the maze where the pirate leaves his treasure chest.\"", 66 },
    { "Hmmm, this looks like a clue, which means it'll cost you 10 points to\r\nread it.  Should I go ahead and read it anyway?", 118 },
    { "It says, \"there is something strange about this place, such that one\r\nof the words I've always known now has a new effect.\"", 123 },
    { "It says the same thing it did before.", 37 },
    { "I'm afraid I don't understand.", 30 },
    { "\"Congratulations on bringing light into the Dark-Room!\"", 55 },
    { "You strike the mirror a resounding blow, whereupon it shatters into a\r\nmyriad tiny fragments.", 93 },
    { "You have taken the vase and hurled it delicately to the ground.", 63 },
    { "You prod the nearest dwarf, who wakes up grumpily, takes one look at\r\nyou, curses, and grabs for his axe.", 105 },
    { "Is this acceptable?", 19 },
    { "There's no point in suspending a demonstration game.", 52 },
    { "You awaken only to discover your bits have been dissolving while you\r\nslept.  You disappear in a cloud of greasy black smoke.", 125 }
};

struct text ctext[CLSMAX] = {
    { "You are obviously a rank amateur.  Better luck next time.", 57 },
    { "Your score qualifies you as a Novice class Adventurer.", 54 },
    { "You have achieved the rating: \"Experienced Adventurer\".", 55 },
    { "You may now consider yourself a \"Seasoned Adventurer\".", 54 },
    { "You have reached \"Junior Master\" status.", 40 },
    { "Your score puts you in Master Adventurer Class C.", 49 },
    { "Your score puts you in Master Adventurer Class B.", 49 },
    { "Your score puts you in Master Adventurer Class A.", 49 },
    { "All of Adventuredom gives tribute to you, Adventurer Grandmaster!", 65 }
};

struct text mtext[MAGSIZ] = {
    { "A large cloud of green smoke appears in front of you.  It clears away\r\nto reveal a tall wizard, clothed in grey.  He fixes you with a steely\r\nglare and declares, \"This adventure has lasted too long.\"  With that\r\nhe makes a single pass over you with his hands, and everything around\r\nyou fades away into a grey nothingness.", 322 },
    { "Even wizards have to wait longer than that!", 43 },
    { "I'm terribly sorry, but Colossal Cave is closed.  Our hours are:", 64 },
    { "Only wizards are permitted within the cave right now.", 53 },
    { "We do allow visitors to make short explorations during our off hours.\r\nWould you like to do that?", 97 },
    { "Colossal Cave is open to regular adventurers at the following hours:", 68 },
    { "Very well.", 10 },
    { "Only a wizard may continue an adventure this soon.", 50 },
    { "I suggest you resume your adventure at a later time.", 52 },
    { "Do you wish to see the hours?", 29 },
    { "Do you wish to change the hours?", 32 },
    { "New magic word (null to leave unchanged):", 41 },
    { "New magic number (null to leave unchanged):", 43 },
    { "Do you wish to change the message of the day?", 45 },
    { "Okay.  You can save this version now.", 37 },
    { "Are you a wizard?", 17 },
    { "Prove it!  Say the magic word!", 30 },
    { "That is not what I thought it was.  Do you know what I thought it was?", 70 },
    { "Oh dear, you really *are* a wizard!  Sorry to have bothered you . . .", 69 },
    { "Foo, you are nothing but a charlatan!", 37 },
    { "New hours specified by defining \"prime time\".  Give only the hour\r\n(E.g. 14, not 14:00 or 2pm).  Enter a negative number after last pair.", 137 },
    { "New hours for Colossal Cave:", 28 },
    { "Limit lines to 70 chars.  End with null line.", 45 },
    { "Line too long, retype:", 22 },
    { "Not enough room for another line.  Ending message here.", 55 },
    { "Do you wish to (re)schedule the next holiday?", 45 },
    { "To begin how many days from today?", 34 },
    { "To last how many days (zero if no holiday)?", 43 },
    { "To be called what (up to 20 characters)?", 40 },
    { "Too small!  Assuming minimum value (45 minutes).", 48 },
    { "Break out of this and save your core-image.", 43 }
};

#endif